[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "multi-cloud"
version = "0.1.0"
description = "Multi-cloud serverless framework"
requires-python = ">=3.9"
license = "MIT"
authors = [
    {name = "Your Name", email = "you@example.com"}
]
dynamic = ["readme"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/multi_cloud"]